name: Deploy Website
on:
  push:
    branches:
    - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          repository: theJaxon/GitHub_Actions

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Test Code
        run: npm run test